sudo: true
dist: trusty
language: c
services:
    - docker

script:
    - travis_retry docker pull cstanfill/silvos:latest
    - travis_retry docker build -t silvos .
    - docker run -e KERNEL_OPT -e USER_OPT --rm -t silvos /bin/sh -c "cd /root/silvos; make clean; make test"

env:
    - USER_OPT=-O0 KERNEL_OPT=-O0
    - USER_OPT=-O0 KERNEL_OPT=-O2
    - USER_OPT=-O0 KERNEL_OPT=-O3
    - USER_OPT=-O0 KERNEL_OPT="-O3 -flto"
    - USER_OPT=-O2 KERNEL_OPT=-O0
    - USER_OPT=-O2 KERNEL_OPT=-O2
    - USER_OPT=-O2 KERNEL_OPT=-O3
    - USER_OPT=-O2 KERNEL_OPT="-O3 -flto"
